#!/usr/bin/bash
# SPDX-FileCopyrightText: 2024 Yuuki Ishizaka
# SPDX-License-Identifier: BSD-3-Clausea

name: ROS2 CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  # 環境をUbuntu 22.04に固定

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        run: |
          sudo apt update
          sudo apt install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu jammy main" > /etc/apt/sources.list.d/ros2.list'
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions

      - name: Create ROS 2 workspace and move package
        run: |
          mkdir -p ~/ros2_ws/src
          mv * ~/ros2_ws/src/  # リポジトリの内容をsrcに移動
          cd ~/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build
          source ~/ros2_ws/install/setup.bash

      - name: Build and Test
        run: |
          chmod +x ~/ros2_ws/src/test/test.bash
          ~/ros2_ws/src/test/test.bash

