name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのクローン
    - name: Checkout repository
      uses: actions/checkout@v3

    # ROS 2 Humble 環境をセットアップ
    - name: Setup ROS 2 environment
      run: |
        sudo apt update && sudo apt install -y curl gnupg lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop python3-colcon-common-extensions
        source /opt/ros/humble/setup.bash

    # ROS 2 ワークスペースを構築
    - name: Build the workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

    # テストの実行
    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test
        colcon test-result --verbose

