

name: ROS 2 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up ROS 2 Humble
        run: |
          sudo apt update && sudo apt install -y python3-colcon-common-extensions
          source /opt/ros/humble/setup.bash
      
      - name: Build ROS 2 package
        run: |
          colcon build --symlink-install
          source install/setup.bash
      
      - name: Run tests
        run: ./test.bash
